version: '3.8'

services:
  nextjs-app:
    container_name: code-breeze
    build: .
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: 'npm run dev'
