version: '3'

services:
  code-breeze:
    container_name: code-breeze
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5151:3000'
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
